### ISSUE TITLE
Generate absolute URIs

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/kibana-cf-auth-proxy#6]
In order to [reason/outcome/goal], we need to configure our server name so we can build absolute URIs.

## Acceptance Criteria
* [ ] GIVEN [a precondition] \
  AND [another precondition]
  WHEN [test step] \
  AND [test step] \
  THEN [verification step] \
  AND [verification step]

--- 

## Security considerations
[note any potential changes to security boundaries, practices, documentation, risk that arise directly from this story]

## Implementation sketch
[links to background notes, sketches, and/or relevant documentation
* [ ] [first thing to do]
* [ ] [another thing to do]

**Comment by mogul** [comment]
Closing for now; will reopen if it looks like it's necessary when we write our new opensearch deployment.
